version: '3.8'

services:
  spring-app:
    container_name: spring-server
    image: ${DOCKER_USERNAME}/inffy-server:latest
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - SPRING_REDIS_HOST = ${REDIS_HOST}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

  redis:
    container_name: inffy-redis
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge